name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  schedule:
    - cron: '27 * * * *
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://example.com/"